set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE STRING "")
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE STRING "")

set(CMAKE_C_FLAGS_DEBUG_INIT "-Og -ggdb")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS -Og -ggdb")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-D_FORTIFY_SOURCE=2")
