set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE STRING "")
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE STRING "")

set(CMAKE_CXX_FLAGS_DEBUG "-D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS")
set(CMAKE_CXX_FLAGS_RELEASE "-D_FORTIFY_SOURCE=2")
