name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GHCR_URL_WITH_UPPERCASE: ghcr.io/${{ github.repository }}
jobs:
  build-devcontainer-image:
    name: Build devcontainer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Convert GHCR url to lower case
        run: echo "GHCR_URL=${GHCR_URL_WITH_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.GHCR_URL }}
          cacheFrom: ${{ env.GHCR_URL }}
          push: always
  make-release-build:
    name: Make release build
    needs: build-devcontainer-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Convert GHCR url to lower case
        run: echo "GHCR_URL=${GHCR_URL_WITH_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make release build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.GHCR_URL }}
          runCmd: |
            cmake --preset clang-release
            cmake --build --preset clang-release-build
  make-debug-build:
    name: Make debug build
    needs: build-devcontainer-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Convert GHCR url to lower case
        run: echo "GHCR_URL=${GHCR_URL_WITH_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make debug build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.GHCR_URL }}
          runCmd: |
            cmake --preset clang-debug
            cmake --build --preset clang-debug-build
      - name: Upload debug build directory
        uses: actions/upload-artifact@v4
        with:
          name: clang-debug-build
          path: build/clang-debug
  run-tests:
    name: Run tests
    needs: make-debug-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Convert GHCR url to lower case
        run: echo "GHCR_URL=${GHCR_URL_WITH_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download debug build directory
        uses: actions/download-artifact@v4
        with:
          name: clang-debug-build
          path: build/clang-debug
      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.GHCR_URL }}
          runCmd: |
            ctest --preset clang-debug-test
