name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GHCR_URL_WITH_UPPERCASE: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build-devcontainer-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Convert GHCR url to lower case
        run: echo "GHCR_URL=${GHCR_URL_WITH_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.GHCR_URL }}
          cacheFrom: ${{ env.GHCR_URL }}
          push: always
  build:
    needs: build-devcontainer-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Convert GHCR url to lower case
        run: echo "GHCR_URL=${GHCR_URL_WITH_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.GHCR_URL }}
          runCmd: |
            cmake --preset clang-release
            cmake --build --preset clang-release-build
      - name: Debug build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.GHCR_URL }}
          runCmd: |
            cmake --preset clang-debug
            cmake --build --preset clang-debug-build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Convert GHCR url to lower case
        run: echo "GHCR_URL=${GHCR_URL_WITH_UPPERCASE@L}" >> ${GITHUB_ENV}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug build
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.GHCR_URL }}
          runCmd: |
            cmake --preset clang-debug
            cmake --build --preset clang-debug-build
      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ${{ env.GHCR_URL }}
          runCmd: |
            ctest --preset clang-debug-test
